# Copyright (c) Holger Just
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE.txt file for details.

name: CI
permissions: {}

on:
  pull_request:
  push:
    paths-ignore:
      - README.md
      - CHANGELOG.md

jobs:
  rspec:
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ruby:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
          - ruby-head

          - jruby-9.4
          - jruby-10.0
        coverage:
          - 1
        retryable:
          - 0

        include:
          - ruby: jruby-9.4.0.0
            os: ubuntu-22.04
            retryable: 0
            coverage: 1

          - ruby: truffleruby
            os: ubuntu-latest
            retryable: 1
            coverage: 1

          - ruby: truffleruby+graalvm
            os: ubuntu-latest
            retryable: 1
            coverage: 1

          - ruby: truffleruby-22
            os: ubuntu-22.04
            retryable: 1
            coverage: 0

          - ruby: truffleruby+graalvm-22
            os: ubuntu-22.04
            retryable: 1
            coverage: 0

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}

    permissions:
      contents: read

    env:
      BUNDLE_WITHOUT: "development:doc"

      COVERAGE: ${{ matrix.coverage }}
      JRUBY_OPTS: "--dev --debug"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run specs
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: ${{ matrix.retryable && 3 || 1 }}
          retry_wait_seconds: 1
          continue_on_error: true
          command: bundle exec rake spec

      - name: Coveralls Parallel
        if: ${{ matrix.coverage == 1 }}
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: rspec-${{ matrix.os }}-${{ matrix.ruby }}
          parallel: true

  coverage:
    name: Coverage
    needs: rspec
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
